### ISSUE TITLE
Empty script

### ISSUE THREAD

**Issue by erkanatsayranbekov** [TransactionTransformer/TransactionTransformer#1]
`summary_data.sh` file located in [TransactionTransformer/dataset/preprocess/total ](https://github.com/TransactionTransformer/TransactionTransformer/blob/main/dataset/preprocess/total/summary_data.sh) is empty

**Comment by TransactionTransformer** [comment]
Thank you for pointing out the missing files. "summary_data.sh" was meant to be a README, with a dropbox link of summary data files.
We will update README shortly once the missing summary data are uploaded.
